### ISSUE TITLE
Create a list of geohashes for a bounding box

### ISSUE THREAD

**Issue by Zverik** [anovis/proximity_hash#10]
Given `{minLat, minLon, maxLat, maxLon, precision}`, I'd like to have a list of geohashes for that.

**Comment by anovis** [comment]
Sorry I missed this. That makes sense. Will see what I can do

**Comment by anovis** [comment]
have a pr for it! I am not able to verify 100%, so if you have some test cases I can add and look at that would be great @Zverik .
