### ISSUE TITLE
createGeohashes returns duplicate geohashes

### ISSUE THREAD

**Issue by yulkin2002** [anovis/proximity_hash#2]
tried createGeohashes(43.649093099999995, -79.42056769999999, 4000, 5);

result: [dpz83, dpz82, dpz83, dpz2r, dpz89, dpz81, dpz88, dpz80, dpz89, dpz81, dpz2x, dpz2p]

three of these are duplicates, is this intended?
dpz83,dpz89,dpz81

**Comment by anovis** [comment]
thanks for reporting @yulkin2002 . this is not intended so will investigate and provide a fix.

**Comment by anovis** [comment]
was able to fix the bug @yulkin2002 . please try version 1.1.0 for the fix

**Comment by yulkin2002** [comment]
@anovis thank you for a quick fix, it works now. Also, thank you for creating and publishing this package, it is very useful!
